# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "opstheatre"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  end

  config.vm.define :opstheatre do |ops|
    ops.vm.hostname = 'opstheatre.olindata.com'
    ops.vm.network "private_network", ip: "192.168.56.10"
  end

  config.vm.provision "shell",
    inline: "/root/setup.sh"

  config.vm.post_up_message = "OpsTheatre is now running and should be accessible from your browser at address http://192.168.56.10:3030"
end
